[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "BeatSaber-Downloader"
version = "2.0"
dependencies = [
    "colorama",
    "requests",
    'importlib-metadata; python_version<"3.8"',
]

[tool.setuptools.packages]
find = {}

